GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjAxOTczMjc2fQ.EKC9FT3YqKdBxhafVXuiyv3DKkkHnYoyo7yARDADg4k
###

POST http://localhost:3001/login
Content-Type: application/json

{
    "username":"Jim"
}